[build]
target = "riscv64gc-unknown-none-elf"

[test]
target = "x86_64-unknown-linux-gnu"

[target.riscv64gc-unknown-none-elf]
rustflags = ["-C", "link-arg=-Tlinker.ld", "--emit=asm"]

[check]
allTargets = false

[unstable]
profile-rustflags = true