[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = ["-C", "relocation-model=pic", "-C", "link-arg=-Tlinker.ld", "--emit=asm", "--emit=obj"]

[check]
allTargets = false

[unstable]
profile-rustflags = true